services:
  db:
    image: mysql:8
    container_name: school-erp-db
    restart: unless-stopped
    environment:
      MYSQL_USER: schoolerp
      MYSQL_PASSWORD: schoolerp
      MYSQL_DATABASE: school_erp
      MYSQL_ROOT_PASSWORD: schoolerp
    ports:
      - '3306:3306'
    volumes:
      - school_erp_mysqldata:/var/lib/mysql
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost -u schoolerp -pschoolerp']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  school_erp_mysqldata:
